general:
  general:
    backend: default         # The matploblib backend used for visualization. `default` uses the system default, can specifiy specific backend (e.g. TKAgg, Qt5Agg, WXAgg).
plots_search:
  dynesty:
    corner: true             # Output corner figure (using anestetic) during a non-linear search fit?
    cornerpoints: false      # Output Dynesty cornerpoints figure during a non-linear search fit?
    runplot: true            # Output Dynesty runplot figure during a non-linear search fit?
    traceplot: true          # Output Dynesty traceplot figure during a non-linear search fit?
  emcee:
    corner: true             # Output corner figure (using corner.py) during a non-linear search fit?
    likelihood_series: true  # Output likelihood series figure during a non-linear search fit?
    time_series: true        # Output time series figure during a non-linear search fit?
    trajectories: true       # Output trajectories figure during a non-linear search fit?
  pyswarms:
    contour: true            # Output contour figure during a non-linear search fit?
    cost_history: true       # Output cost_history figure during a non-linear search fit?
    time_series: true        # Output time_series figure during a non-linear search fit?
    trajectories: true       # Output trajectories figure during a non-linear search fit?
  ultranest:
    corner: true             # Output corner figure (using anestetic) during a non-linear search fit?
    runplot: true            # Output Ultranest runplot figure during a non-linear search fit?
    traceplot: true          # Output Ultranest traceplot figure during a non-linear search fit?
  zeus:
    corner: true             # Output corner figure (using corner.py) during a non-linear search fit?
    likelihood_series: true  # Output likelihood series figure during a non-linear search fit?
    time_series: true        # Output time series figure during a non-linear search fit?
    trajectories: true       # Output trajectories figure during a non-linear search fit?