export WORKSPACE=/home/jammy/PycharmProjects/PyAuto/autofit_workspace/howtofit/chapter_1_introduction/

python3 tutorial_1_model_mapping/tutorial_1_model_mapping.py
py_to_notebook tutorial_1_model_mapping/tutorial_1_model_mapping.py

python3 tutorial_2_model_fitting/tutorial_2_model_fitting.py
py_to_notebook tutorial_2_model_fitting/tutorial_2_model_fitting.py

python3 tutorial_3_non_linear_search/tutorial_3_non_linear_search.py
py_to_notebook tutorial_3_non_linear_search/tutorial_3_non_linear_search.py

python3 tutorial_4_visualization_masking/tutorial_4_visualization_masking.py
py_to_notebook tutorial_4_visualization_masking/tutorial_4_visualization_masking.py

python3 tutorial_5_complex_models/tutorial_5_complex_models.py
py_to_notebook tutorial_5_complex_models/tutorial_5_complex_models.py

python3 tutorial_6_phase_customization/tutorial_6_phase_customization.py
py_to_notebook tutorial_6_phase_customization/tutorial_6_phase_customization.py

python3 tutorial_7_aggregator/tutorial_7_aggregator_part_1.py
py_to_notebook tutorial_7_aggregator/tutorial_7_aggregator_part_1.py

python3 tutorial_7_aggregator/tutorial_7_aggregator_part_2.py
py_to_notebook tutorial_7_aggregator/tutorial_7_aggregator_part_2.py

rm tutorial_*/*/*/*.ipynb

export WORKSPACE=/home/jammy/PycharmProjects/PyAuto/autolens_workspace/