ModelComponent0:
  parameter0:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 1.0
  parameter1:
    type: LogUniform
    lower_limit: 1.0e-06
    upper_limit: 1000000.0
  parameter2:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 25.0
ModelComponent1:
  parameter0:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 1.0
  parameter1:
    type: LogUniform
    lower_limit: 1.0e-06
    upper_limit: 1000000.0
  parameter2:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 1.0
